# Generated by Django 4.2 on 2023-04-18 08:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bar.baseclass')),
                ('category', models.CharField(choices=[('ALCO', 'Алкогольные напитки'), ('NONALCO', 'Безалкогольные напитки'), ('SNACK', 'Закуски'), ('MAIN', 'Основные блюда')], default='MAIN', max_length=7, verbose_name='Категория позиции')),
                ('title', models.CharField(max_length=255, verbose_name='Название позиции')),
                ('weight_volume', models.CharField(default=0, max_length=255, verbose_name='Объем/Вес')),
                ('units', models.CharField(choices=[('N', '-'), ('G', 'гр.'), ('M', 'мл.')], default='N', max_length=1, verbose_name='Единицы измерения')),
                ('energy_value', models.CharField(default=0, max_length=255, verbose_name='Энергетическая ценность в кКл')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='imgs', verbose_name='Фото')),
            ],
            bases=('bar.baseclass',),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bar.baseclass')),
                ('title', models.CharField(max_length=255, verbose_name='Название акции')),
                ('description', models.TextField(blank=True, verbose_name='Условия акции')),
            ],
            bases=('bar.baseclass',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bar.baseclass')),
                ('from_username', models.CharField(max_length=255, verbose_name='Отзыв от')),
                ('review_content', models.TextField(verbose_name='Отзыв')),
            ],
            bases=('bar.baseclass',),
        ),
    ]
