# Generated by Django 4.2 on 2023-04-19 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bar.baseclass')),
                ('user_id', models.CharField(max_length=255, verbose_name='User_id пользователя')),
                ('bonus_amount', models.FloatField(verbose_name='Количество бонусов')),
            ],
            bases=('bar.baseclass',),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bar.baseclass')),
                ('user_id', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('order_data', models.TextField()),
            ],
            bases=('bar.baseclass',),
        ),
    ]
